server:
  port: 8083
  #连接超时，单位为毫秒，-1永不超时
  tomcat:
    connection-timeout: 6000
    uri-encoding: utf-8
    max-connections: 10000
    threads:
      min-spare: 10
      max: 220 #最大220个并发，可以达到不丢包（可以自己实测），默认为200。

spring:
  application:
    name: springboot-spiderAdmin
  mvc:
    view:
      prefix: /static/page/
      suffix: .html
    static-path-pattern: static/**
  resources:
    static-locations: classpath:static/
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
  datasource:
    name: let_us_chat
    url: jdbc:mysql://localhost:3306/webspider?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: mjy2018
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  mapper-locations: classpath*:cn/cxnxs/webspider/web/mapper/xml/*Mapper.xml
  global-config:
    # 逻辑删除配置
    db-config:
      # 删除前
      logic-not-delete-value: 1
      # 删除后
      logic-delete-value: 0
logging:
    config: classpath:logback.xml
    level:
      root: INFO
